from fpdf import FPDF


def make_pdf(filename: str, payment_system: str, blockchain_tx_id: str | None = None) -> None:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", size=14)

    pdf.cell(0, 10, f"Test Invoice ({payment_system.upper()})", ln=True, align="C")
    pdf.ln(8)

    pdf.set_font("Arial", size=12)
    pdf.cell(0, 8, "Seller: Example Seller BV", ln=True)
    pdf.cell(0, 8, "Buyer: Test Buyer BV", ln=True)
    pdf.cell(0, 8, "Invoice #: TEST-001", ln=True)
    pdf.cell(0, 8, "Date: 2026-01-30", ln=True)
    pdf.ln(6)

    pdf.cell(0, 8, "Description: Sample service", ln=True)
    pdf.cell(0, 8, "Amount: EUR 100.00", ln=True)
    pdf.ln(6)

    pdf.cell(0, 8, f"Payment system: {payment_system}", ln=True)
    if blockchain_tx_id:
        pdf.cell(0, 8, f"Blockchain TX ID: {blockchain_tx_id}", ln=True)

    pdf.ln(12)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 6, "This PDF is generated for testing Web2 vs Web3 invoice rendering.\nGenerated by scripts/generate_test_pdfs.py.")

    pdf.output(filename)


if __name__ == "__main__":
    make_pdf("invoice_web2.pdf", "web2")
    make_pdf("invoice_web3.pdf", "web3", blockchain_tx_id="0xDEADBEEF1234567890")
    print("Generated invoice_web2.pdf and invoice_web3.pdf")
